server:
  port: 8090
  context-path: /
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.96.40.94:1521:XE
    username: ht1706
    password: ht1706
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: cn.tedu.pojo
  
