server:
  port: 8090
  context-path: /
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
<<<<<<< HEAD
    url: jdbc:oracle:thin:@172.96.40.94:1521:XE
    username: ht1706
    password: ht1706
=======
<<<<<<< HEAD
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: traval
    password: traval
=======
    url: jdbc:oracle:thin:@172.96.40.94:1521:XE
    username: ht1706
    password: ht1706
>>>>>>> origin/wanganqi
>>>>>>> 5ffa28fd9021f521097a43c251f3566a8a2a7fd3
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml